workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # تحديد المسارات التي أكدها السجل السابق
          QT_PATH_FOUND="/Users/builder/clone/6.6.0/ios"
          QT_HOST_PATH="/Users/builder/clone/6.6.0/macos"

          cd MIRA/client
          mkdir -p build && cd build
          
          # الحل الذهبي: استخدام qt.toolchain.cmake
          # هذا الملف يحل مشكلة Pcre2 و Core تلقائياً
          cmake .. \
            -G Xcode \
            -DCMAKE_TOOLCHAIN_FILE="$QT_PATH_FOUND/lib/cmake/Qt6/qt.toolchain.cmake" \
            -DQT_HOST_PATH="$QT_HOST_FOUND" \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO \
            -DCMAKE_SYSTEM_NAME=iOS
          
          # البناء
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa