workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # 1. تحديد المسارات المطلقة التي حصلنا عليها من السجل السابق
          QT_IOS="/Users/builder/clone/6.6.0/ios"
          QT_MAC="/Users/builder/clone/6.6.0/macos"
          
          # 2. إضافة أدوات Qt للمسار العام
          export PATH=$QT_MAC/bin:$QT_IOS/bin:$PATH
          
          cd MIRA/client
          mkdir -p build && cd build
          
          # 3. استخدام سكريبت qt-cmake الرسمي (هذا هو الحل السحري لمشكلة GLESv2)
          # هذا السكريبت يضبط كل التبعيات تلقائياً
          $QT_IOS/bin/qt-cmake .. \
            -G Xcode \
            -DQT_HOST_PATH=$QT_MAC \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # 4. البناء الفعلي
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa