workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
        BUNDLE_ID: "com.mira.app.client" # هوية التطبيق
      xcode: latest
    scripts:
      - name: Install Qt6 with all required modules
        script: |
          pip3 install aqtinstall
          # إضافة shadertools و declarative و qt5compat لضمان وجود كل التبعيات
          aqt install-qt mac desktop $QT_VERSION -m qt5compat shadertools declarative
          aqt install-qt mac ios $QT_VERSION -m qt5compat shadertools declarative
      - name: Configure and Build MIRA_Client
        script: |
          QT_IOS="/Users/builder/clone/6.6.0/ios"
          QT_MAC="/Users/builder/clone/6.6.0/macos"
          
          export PATH=$QT_MAC/bin:$PATH
          
          cd MIRA/client
          mkdir -p build && cd build
          
          # تشغيل qt-cmake مع إضافة موديول ShaderTools وتعيين Bundle ID
          $QT_IOS/bin/qt-cmake .. \
            -G Xcode \
            -DQT_HOST_PATH=$QT_MAC \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DXCODE_ATTRIBUTE_PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # البناء النهائي
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa