workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # تحديد المسارات
          QT_PATH=$ROOT_DIR/$QT_VERSION/ios
          QT_HOST_PATH=$ROOT_DIR/$QT_VERSION/macos
          
          # الدخول إلى المجلد الذي يحتوي على ملف CMakeLists.txt
          cd MIRA/client
          
          mkdir -p build
          cd build
          
          # بناء المشروع من داخل المجلد الفرعي
          cmake .. \
            -G Xcode \
            -DCMAKE_PREFIX_PATH=$QT_PATH \
            -DQT_HOST_PATH=$QT_HOST_PATH \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa