workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # تحديد المسارات بناءً على هيكلية aqtinstall المعروفة
          export QT_ROOT=$ROOT_DIR/6.6.0
          export QT_IOS_DIR=$QT_ROOT/ios
          export QT_HOST_DIR=$QT_ROOT/macos
          
          # الدخول للمجلد الذي يحتوي على CMakeLists.txt
          cd MIRA/client
          
          mkdir -p build && cd build
          
          # تشغيل CMake مع المسارات الصحيحة
          cmake .. \
            -G Xcode \
            -DCMAKE_PREFIX_PATH=$QT_IOS_DIR \
            -DQT_HOST_PATH=$QT_HOST_DIR \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DQt6_DIR=$QT_IOS_DIR/lib/cmake/Qt6 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # البناء النهائي
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa