workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          # تثبيت النسختين (الماك للأدوات والأيفون للمكتبات)
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # 1. تحديد المسارات المطلقة التي أكدتها السجلات
          QT_IOS="/Users/builder/clone/6.6.0/ios"
          QT_MAC="/Users/builder/clone/6.6.0/macos"
          
          # 2. إضافة أدوات الماك للمسار (للوصول لـ moc و uic)
          export PATH=$QT_MAC/bin:$PATH
          
          cd MIRA/client
          mkdir -p build && cd build
          
          # 3. الحل النهائي: استخدام qt-cmake مع تحديد الـ Host والـ Sysroot
          # هذا السكريبت هو "المفتاح" لحل مشكلة GLESv2 و Core و Gui
          $QT_IOS/bin/qt-cmake .. \
            -G Xcode \
            -DQT_HOST_PATH=$QT_MAC \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # 4. بناء المشروع وتوليد ملف الـ .app
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa