workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # 1. تحديد المسارات المطلقة لـ Qt
          QT_IOS_DIR=$ROOT_DIR/$QT_VERSION/ios
          QT_HOST_DIR=$ROOT_DIR/$QT_VERSION/macos
          
          # 2. الدخول لمجلد المشروع
          cd MIRA/client
          
          mkdir -p build
          cd build
          
          # 3. تشغيل CMake مع إضافة كل المكتبات المطلوبة (Core5Compat, etc)
          cmake .. \
            -G Xcode \
            -DCMAKE_PREFIX_PATH="$QT_IOS_DIR;$QT_IOS_DIR/lib/cmake" \
            -DQt6_DIR="$QT_IOS_DIR/lib/cmake/Qt6" \
            -DQT_HOST_PATH="$QT_HOST_DIR" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # 4. البناء الفعلي باستخدام التوليد الذي قام به CMake
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa