workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # 1. استخدام المسارات التي أثبتت نجاحها في الخطوة السابقة
          QT_PATH_FOUND="/Users/builder/clone/6.6.0/ios"
          QT_HOST_FOUND="/Users/builder/clone/6.6.0/macos"

          echo "Using Qt iOS Path: $QT_PATH_FOUND"
          
          cd MIRA/client
          mkdir -p build && cd build
          
          # 2. إضافة مسار الـ Modules لـ CMake بشكل مباشر (هذا سيحل مشكلة Core)
          cmake .. \
            -G Xcode \
            -DCMAKE_PREFIX_PATH="$QT_PATH_FOUND;$QT_PATH_FOUND/lib/cmake" \
            -DQT_HOST_PATH="$QT_HOST_FOUND" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DQt6_DIR="$QT_PATH_FOUND/lib/cmake/Qt6" \
            -DQt6Core_DIR="$QT_PATH_FOUND/lib/cmake/Qt6Core" \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # 3. البناء
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa