workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          # إضافة -m qt5compat لتحميل المكتبة الناقصة للنسختين
          aqt install-qt mac desktop $QT_VERSION -m qt5compat
          aqt install-qt mac ios $QT_VERSION -m qt5compat
      - name: Configure and Build MIRA_Client
        script: |
          # تحديد المسارات المطلقة
          QT_IOS="/Users/builder/clone/6.6.0/ios"
          QT_MAC="/Users/builder/clone/6.6.0/macos"
          
          export PATH=$QT_MAC/bin:$PATH
          
          cd MIRA/client
          mkdir -p build && cd build
          
          # استخدام qt-cmake الرسمي مع تفعيل البحث عن المكتبات الإضافية
          $QT_IOS/bin/qt-cmake .. \
            -G Xcode \
            -DQT_HOST_PATH=$QT_MAC \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # البناء
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa