workflows:
  ios-qt6-cmake-workflow:
    name: Build MIRA_Client iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        QT_VERSION: "6.6.0"
      xcode: latest
    scripts:
      - name: Install Qt6 for iOS and macOS
        script: |
          pip3 install aqtinstall
          aqt install-qt mac desktop $QT_VERSION
          aqt install-qt mac ios $QT_VERSION
      - name: Configure and Build MIRA_Client
        script: |
          # البحث الديناميكي عن مسار Qt لتجنب أخطاء المسارات الثابتة
          QT_IOS_PATH=$(find $ROOT_DIR -name "Qt6Config.cmake" | grep "ios" | head -n 1 | xargs dirname | xargs dirname | xargs dirname | xargs dirname)
          QT_HOST_PATH=$(find $ROOT_DIR -name "Qt6Config.cmake" | grep "macos" | head -n 1 | xargs dirname | xargs dirname | xargs dirname | xargs dirname)

          echo "Qt iOS Path: $QT_IOS_PATH"
          echo "Qt Host Path: $QT_HOST_PATH"

          cd MIRA/client
          mkdir -p build && cd build
          
          # إعداد المشروع مع تمرير المسارات التي وجدناها
          cmake .. \
            -G Xcode \
            -DCMAKE_PREFIX_PATH="$QT_IOS_PATH" \
            -DQT_HOST_PATH="$QT_HOST_PATH" \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
          
          # البناء
          cmake --build . --config Release -- -sdk iphoneos
    artifacts:
      - MIRA/client/build/Release-iphoneos/*.app
      - MIRA/client/build/**/*.ipa