pragma Singleton
import QtQuick

QtObject {
    property string currentLanguage: "ar" // Default to Arabic
    
    // Translation data
    readonly property var translations: {
        "en": {
            "home": "Home",
            "search": "Search",
            "activity": "Activity",
            "profile": "Profile",
            "settings": "Settings",
            "language": "Language",
            "notifications": "Notifications",
            "privacy": "Privacy",
            "account": "Account",
            "followInvite": "Follow and invite friends",
            "darkMode": "Dark Mode",
            "logout": "Log out",
            "editProfile": "Edit profile",
            "shareProfile": "Share profile",
            "followers": "Followers",
            "following": "Following",
            "replies": "Replies",
            "threads": "MIRA",
            "newThread": "New thread",
            "post": "Post",
            "cancel": "Cancel",
            "done": "Done",
            "save": "Save Changes",
            "name": "Name",
            "bio": "Bio",
            "username": "Username",
            "changeColor": "Change color",
            "searchPlaceholder": "Search",
            "messages": "Messages",
            "all": "All",
            "follows": "Follows",
            "mentions": "Mentions",
            "quotes": "Quotes",
            "reposts": "Reposts",
            "verified": "Verified",
            "likesStat": "likes",
            "repliesStat": "replies",
            "followContacts": "Follow contacts",
            "inviteSMS": "Invite friends by SMS",
            "inviteEmail": "Invite friends by email",
            "inviteOther": "Invite friends by...",
            "hiddenWords": "Hidden Words",
            "offensiveHeader": "Offensive words and phrases",
            "offensiveDesc": "Hide comments that contain words, phrases or emojis in your custom list, and those commonly reported as offensive.",
            "hideOffensiveComments": "Hide offensive comments",
            "advancedFiltering": "Advanced comment filtering",
            "customWordsHeader": "Custom words and phrases",
            "manageCustom": "Manage custom words and phrases",
            "hideReplies": "Hide replies",
            "blockedProfiles": "Blocked Profiles",
            "blockedDesc": "You can block someone to stop them from finding your profile, posts or story on Threads.",
            "unblock": "Unblock",
            "accountHeader": "Account",
            "accountCenterHeader": "Account Center",
            "accountCenterDesc": "Manage your connected experiences across Meta technologies.",
            "personalDetails": "Personal details",
            "passwordSecurity": "Password and security",
            "infoPermissions": "Your information and permissions",
            "adPreferences": "Ad preferences",
            "payments": "Payments",
            "deactivateDelete": "Deactivate or delete profile",
            "privateProfile": "Private profile",
            "everyone": "Everyone",
            "muted": "Muted",
            "profilesFollow": "Profiles you follow",
            "otherPrivacy": "Other privacy settings",
            "privacyLongDesc": "Some settings, like account privacy, apply to both Threads and Instagram.",
            "hideLikes": "Hide likes",
            "pauseAll": "Pause all",
            "threadsReplies": "MIRA and replies",
            "followFollowers": "Following and followers",
            "directMessages": "Direct messages",
            "instagram": "Instagram",
            "fromThreads": "From MIRA",
            "emailNotifications": "Email notifications",
            "feedbackEmails": "Feedback emails",
            "reminderEmails": "Reminder emails",
            "help": "Help",
            "about": "About",
            "helpCenter": "Help Center",
            "reportProblem": "Report a problem",
            "supportRequests": "Support Requests",
            "privacySecurityHelp": "Privacy and Security Help",
            "termsOfUse": "Terms of Use",
            "privacyPolicy": "Privacy Policy",
            "cookiesPolicy": "Cookies Policy",
            "openSourceLibraries": "Open Source Libraries",
            "whatsNew": "What's new?",
            "addToThread": "Add to thread",
            "anyoneCanReply": "Anyone can reply"
        },
        "ar": {
            "home": "الرئيسية",
            "search": "بحث",
            "activity": "النشاط",
            "profile": "الملف الشخصي",
            "settings": "الإعدادات",
            "language": "اللغة",
            "notifications": "التنبيهات",
            "privacy": "الخصوصية",
            "account": "الحساب",
            "followInvite": "متابعة ودعوة الأصدقاء",
            "darkMode": "الوضع الداكن",
            "logout": "تسجيل الخروج",
            "editProfile": "تعديل الملف الشخصي",
            "shareProfile": "مشاركة الملف الشخصي",
            "followers": "المتابعون",
            "following": "يتابع",
            "replies": "الردود",
            "threads": "MIRA",
            "newThread": "خيط جديد",
            "post": "نشر",
            "cancel": "إلغاء",
            "done": "تم",
            "save": "حفظ التغييرات",
            "name": "الاسم",
            "bio": "السيرة الذاتية",
            "username": "اسم المستخدم",
            "changeColor": "تغيير اللون",
            "searchPlaceholder": "بحث",
            "messages": "الرسائل",
            "all": "الكل",
            "follows": "المتابعات",
            "mentions": "الإشارات",
            "quotes": "الاقتباسات",
            "reposts": "إعادات النشر",
            "verified": "موثق",
            "likesStat": "إعجاب",
            "repliesStat": "رد",
            "followContacts": "متابعة جهات الاتصال",
            "inviteSMS": "دعوة أصدقاء عبر SMS",
            "inviteEmail": "دعوة أصدقاء عبر البريد",
            "inviteOther": "دعوة أصدقاء عبر...",
            "hiddenWords": "الكلمات المخفية",
            "offensiveHeader": "الكلمات والعبارات الهجومية",
            "offensiveDesc": "إخفاء التعليقات التي تحتوي على كلمات أو عبارات أو رموز تعبيرية في قائمتك المخصصة.",
            "hideOffensiveComments": "إخفاء التعليقات الهجومية",
            "advancedFiltering": "تصفية التعليقات المتقدمة",
            "customWordsHeader": "كلمات وعبارات مخصصة",
            "manageCustom": "إدارة الكلمات والعبارات المخصصة",
            "hideReplies": "إخفاء الردود",
            "blockedProfiles": "الحسابات المحظورة",
            "blockedDesc": "يمكنك حظر شخص ما لمنعه من العثور على ملفك الشخصي أو منشوراتك على Threads.",
            "unblock": "إلغاء الحظر",
            "accountHeader": "الحساب",
            "accountCenterHeader": "مركز الحساب",
            "accountCenterDesc": "إدارة تجاربك المتصلة عبر تقنيات Meta.",
            "personalDetails": "التفاصيل الشخصية",
            "passwordSecurity": "كلمة السر والأمان",
            "infoPermissions": "معلوماتك وأذوناتك",
            "adPreferences": "تفضيلات الإعلانات",
            "payments": "المدفوعات",
            "deactivateDelete": "إلغاء تنشيط الملف الشخصي أو حذفه",
            "privateProfile": "حساب خاص",
            "everyone": "الكل",
            "muted": "الحسابات المكتومة",
            "profilesFollow": "الحسابات التي تتابعها",
            "otherPrivacy": "إعدادات الخصوصية الأخرى",
            "privacyLongDesc": "تنطبق بعض الإعدادات، مثل خصوصية الحساب، على كل من Threads و Instagram.",
            "hideLikes": "إخفاء تسجيلات الإعجاب",
            "pauseAll": "إيقاف الكل مؤقتاً",
            "threadsReplies": "MIRA والردود",
            "followFollowers": "المتابعة والمتابعون",
            "directMessages": "الرسائل المباشرة",
            "instagram": "Instagram",
            "fromThreads": "من MIRA",
            "emailNotifications": "تنبيهات البريد الإلكتروني",
            "feedbackEmails": "رسائل البريد الإلكتروني للملاحظات",
            "reminderEmails": "رسائل البريد الإلكتروني للتذكير",
            "help": "المساعدة",
            "about": "حول",
            "helpCenter": "مركز المساعدة",
            "reportProblem": "الإبلاغ عن مشكلة",
            "supportRequests": "طلبات الدعم",
            "privacySecurityHelp": "مساعدة بخصوص الخصوصية والأمان",
            "termsOfUse": "شروط الاستخدام",
            "privacyPolicy": "سياسة الخصوصية",
            "cookiesPolicy": "سياسة ملفات تعريف الارتباط",
            "openSourceLibraries": "مكتبات مفتوحة المصدر",
            "whatsNew": "ما الجديد؟",
            "addToThread": "أضف إلى الخيط",
            "anyoneCanReply": "يمكن للجميع الرد"
        }
    }

    // Helper function to get translated string
    function getString(key) {
        let lang = currentLanguage;
        if (!translations[lang]) lang = "en"; // Fallback to English
        return translations[lang][key] || key;
    }
}
